### ISSUE TITLE
Identical nightly release assets names

### ISSUE THREAD

**Issue by SebastianHambura** [arkitektio/orkestrator-next#6]
Would it be possible to add some additional information in the name of the release asset ? 
I now have 2 files calles "orkestrator-next-1.0.6-setup.exe" in my download folder, that were downloaded from 2 differents releases at 2 differents dates - so they actually are distinct. 
Could you append the release tag or the commit hash to the name of the generated binaries ?

**Comment by jhnnsrs** [comment]
Should be fixed now. Releases will now have the release date appended, bit ugly but should work :)
